// Provider-neutral chat types shared by the server orchestrator, the
// provider adapters, and the chat UI. No server-only imports here.

export type ProviderId = "claude" | "gpt" | "gemini";
export type ModelTier = "standard" | "premium" | "flagship";

export interface CatalogModel {
  /** Stable id used by the UI and as the provider API model id. */
  id: string;
  label: string;
  provider: ProviderId;
  providerLabel: string;
  tier: ModelTier;
  enabled: boolean;
}

// See DESIGN.md — Model catalog & tiers. Plan gating of tiers is Phase 5.
export const MODEL_CATALOG: CatalogModel[] = [
  { id: "claude-sonnet-5", label: "Claude Sonnet 5", provider: "claude", providerLabel: "Claude", tier: "standard", enabled: true },
  { id: "claude-opus-4-8", label: "Claude Opus 4.8", provider: "claude", providerLabel: "Claude", tier: "premium", enabled: true },
  { id: "claude-fable-5", label: "Claude Fable 5", provider: "claude", providerLabel: "Claude", tier: "flagship", enabled: true },
  { id: "gpt-5.4", label: "GPT-5.4", provider: "gpt", providerLabel: "GPT", tier: "standard", enabled: true },
  // Premium tier is Claude Opus 4.8 + Gemini 3.1 Pro only — no GPT model.
  { id: "gpt-5.6-sol", label: "GPT-5.6 Sol", provider: "gpt", providerLabel: "GPT", tier: "flagship", enabled: true },
  { id: "gemini-3.5-flash", label: "Gemini 3.5 Flash", provider: "gemini", providerLabel: "Gemini", tier: "standard", enabled: true },
  { id: "gemini-3.1-pro-preview", label: "Gemini 3.1 Pro", provider: "gemini", providerLabel: "Gemini", tier: "premium", enabled: true },
];

export function modelLabel(apiModelId: string): string {
  const match = MODEL_CATALOG.find((m) => apiModelId.startsWith(m.id));
  return match ? match.label : apiModelId;
}

/**
 * Short, merchant-facing status labels per tool, shown while a turn is in
 * progress. Shared by the chat UI (rendering past tool steps) and the server
 * orchestrator (writing the live current_step of the running turn). Kept here
 * — a provider-neutral, client-and-server-safe module — so there is one map.
 */
export const TOOL_STATUS_LABELS: Record<string, string> = {
  fetch_url: "Reading a web page…",
  search_products: "Searching products…",
  get_product: "Reading product details…",
  get_inventory_levels: "Checking inventory levels…",
  get_shipping_setup: "Reading shipping setup…",
  list_discounts: "Reading discounts…",
  read_analytics: "Reading store analytics…",
  list_customers: "Reading customers…",
  generate_customer_csv: "Preparing a customer export…",
  get_shop_info: "Reading store settings…",
  update_shop_policies: "Proposing a policy update…",
  list_themes: "Reading themes…",
  list_theme_files: "Listing theme files…",
  read_theme_file: "Reading theme code…",
  create_product: "Proposing a new product…",
  update_product: "Proposing a product update…",
  delete_product: "Proposing a product deletion…",
  set_inventory_quantity: "Proposing an inventory change…",
  create_shipping_zone: "Proposing a shipping zone…",
  update_shipping_zone: "Proposing a shipping zone update…",
  set_shipping_rate: "Proposing a shipping rate…",
  create_discount_code: "Proposing a discount code…",
  create_bxgy_discount: "Proposing a buy-X-get-Y discount…",
  create_free_shipping_discount: "Proposing a free-shipping discount…",
  update_discount_code: "Proposing a discount update…",
  deactivate_discount_code: "Proposing a discount deactivation…",
  delete_discount_code: "Proposing a discount deletion…",
  generate_image: "Generating an image…",
  upload_image_to_files: "Proposing an image upload…",
};

export interface NeutralToolCall {
  /** Neutral id — the provider's call id when it supplied one. */
  id: string;
  name: string;
  input: Record<string, unknown>;
  /** True when `id` was generated by us because the provider omitted one. */
  syntheticId?: boolean;
}

export interface Attachment {
  name: string;
  mimeType: string;
  /** Raw base64 (no data: prefix). */
  data: string;
}

export interface UserMessage {
  role: "user";
  text: string;
  attachments?: Attachment[];
}

export interface AssistantMessage {
  role: "assistant";
  text: string;
  toolCalls: NeutralToolCall[];
  /** Which provider produced this message (drives faithful replay). */
  provider?: ProviderId;
  /** Display label of the model that actually served this message. */
  modelLabel?: string;
  /**
   * Provider-native payload (Claude content blocks / OpenAI output items /
   * Gemini content). Replayed verbatim on the same provider so
   * reasoning/thinking state survives; other providers rebuild from
   * text + toolCalls.
   */
  raw?: unknown;
}

export interface ToolMessage {
  role: "tool";
  toolCallId: string;
  toolName: string;
  content: string;
  isError?: boolean;
  /** Mirrors NeutralToolCall.syntheticId for the call this answers. */
  syntheticId?: boolean;
}

export type NeutralMessage = UserMessage | AssistantMessage | ToolMessage;

export interface DiffLine {
  type: "add" | "del" | "ctx";
  text: string;
}

export interface PendingWrite {
  toolUseId: string;
  toolName: string;
  input: Record<string, unknown>;
  summary: string[];
  /** Whether the provider omitted a call id (Gemini sometimes does). */
  syntheticId?: boolean;
  /** Line-level before/after diff for theme file edits. */
  diff?: DiffLine[];
  /** Extra warning shown prominently in the approval modal (e.g. live theme). */
  warning?: string;
  /**
   * A generated_images id to render as an inline preview in the approval modal
   * (upload_image_to_files) — the merchant sees the actual image before it is
   * saved to Files.
   */
  previewImageId?: string;
}

export interface UsageEntry {
  provider: ProviderId;
  modelId: string;
  inputTokens: number;
  outputTokens: number;
  /**
   * gpt-image-2 image-generation token breakdown, billed at their own rates
   * (see MODEL_PRICES). Absent for ordinary chat calls.
   */
  imageInputTokens?: number;
  cachedImageInputTokens?: number;
  imageOutputTokens?: number;
}

export interface ChatTurnResult {
  status: "done" | "pending_write" | "refusal" | "error";
  messages: NeutralMessage[];
  pendingWrite?: PendingWrite;
  errorMessage?: string;
  /** One entry per model API call made during this turn (credit ledger). */
  usage: UsageEntry[];
}
