// Provider-neutral chat types shared by the server orchestrator, the
// provider adapters, and the chat UI. No server-only imports here.

export type ProviderId = "claude" | "gpt" | "gemini";
export type ModelTier = "standard" | "premium" | "flagship";

export interface CatalogModel {
  /** Stable id used by the UI and as the provider API model id. */
  id: string;
  label: string;
  provider: ProviderId;
  providerLabel: string;
  tier: ModelTier;
  enabled: boolean;
}

// See DESIGN.md — Model catalog & tiers. Plan gating of tiers is Phase 5.
export const MODEL_CATALOG: CatalogModel[] = [
  { id: "claude-sonnet-5", label: "Claude Sonnet 5", provider: "claude", providerLabel: "Claude", tier: "standard", enabled: true },
  { id: "claude-opus-4-8", label: "Claude Opus 4.8", provider: "claude", providerLabel: "Claude", tier: "premium", enabled: true },
  { id: "claude-fable-5", label: "Claude Fable 5", provider: "claude", providerLabel: "Claude", tier: "flagship", enabled: true },
  { id: "gpt-5.4", label: "GPT-5.4", provider: "gpt", providerLabel: "GPT", tier: "standard", enabled: true },
  // Premium tier is Claude Opus 4.8 + Gemini 3.1 Pro only — no GPT model.
  { id: "gpt-5.6-sol", label: "GPT-5.6 Sol", provider: "gpt", providerLabel: "GPT", tier: "flagship", enabled: true },
  { id: "gemini-3.5-flash", label: "Gemini 3.5 Flash", provider: "gemini", providerLabel: "Gemini", tier: "standard", enabled: true },
  { id: "gemini-3.1-pro-preview", label: "Gemini 3.1 Pro", provider: "gemini", providerLabel: "Gemini", tier: "premium", enabled: true },
];

export function modelLabel(apiModelId: string): string {
  const match = MODEL_CATALOG.find((m) => apiModelId.startsWith(m.id));
  return match ? match.label : apiModelId;
}

export interface NeutralToolCall {
  /** Neutral id — the provider's call id when it supplied one. */
  id: string;
  name: string;
  input: Record<string, unknown>;
  /** True when `id` was generated by us because the provider omitted one. */
  syntheticId?: boolean;
}

export interface Attachment {
  name: string;
  mimeType: string;
  /** Raw base64 (no data: prefix). */
  data: string;
}

export interface UserMessage {
  role: "user";
  text: string;
  attachments?: Attachment[];
}

export interface AssistantMessage {
  role: "assistant";
  text: string;
  toolCalls: NeutralToolCall[];
  /** Which provider produced this message (drives faithful replay). */
  provider?: ProviderId;
  /** Display label of the model that actually served this message. */
  modelLabel?: string;
  /**
   * Provider-native payload (Claude content blocks / OpenAI output items /
   * Gemini content). Replayed verbatim on the same provider so
   * reasoning/thinking state survives; other providers rebuild from
   * text + toolCalls.
   */
  raw?: unknown;
}

export interface ToolMessage {
  role: "tool";
  toolCallId: string;
  toolName: string;
  content: string;
  isError?: boolean;
  /** Mirrors NeutralToolCall.syntheticId for the call this answers. */
  syntheticId?: boolean;
}

export type NeutralMessage = UserMessage | AssistantMessage | ToolMessage;

export interface DiffLine {
  type: "add" | "del" | "ctx";
  text: string;
}

export interface PendingWrite {
  toolUseId: string;
  toolName: string;
  input: Record<string, unknown>;
  summary: string[];
  /** Whether the provider omitted a call id (Gemini sometimes does). */
  syntheticId?: boolean;
  /** Line-level before/after diff for theme file edits. */
  diff?: DiffLine[];
  /** Extra warning shown prominently in the approval modal (e.g. live theme). */
  warning?: string;
}

export interface UsageEntry {
  provider: ProviderId;
  modelId: string;
  inputTokens: number;
  outputTokens: number;
}

export interface ChatTurnResult {
  status: "done" | "pending_write" | "refusal" | "error";
  messages: NeutralMessage[];
  pendingWrite?: PendingWrite;
  errorMessage?: string;
  /** One entry per model API call made during this turn (credit ledger). */
  usage: UsageEntry[];
}
